language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - flake8 treebeard
  - coverage run -m unittest

after_success:
  - bash <(curl -s https://codecov.io/bash)
